"""Add encrypted_access_token to users

Revision ID: c3fa146cf032
Revises: 13cc50e61543
Create Date: 2025-10-27 13:15:43.193433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3fa146cf032'
down_revision: Union[str, Sequence[str], None] = '13cc50e61543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_data_timestamp'), table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('ix_intraday_ltp_timestamp'), table_name='intraday_ltp')
    op.drop_table('intraday_ltp')
    op.add_column('users', sa.Column('encrypted_access_token', sa.LargeBinary(), nullable=True))
    op.alter_column('users', 'mobile_number',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_column('users', 'is_trial_active')
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_trial_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.alter_column('users', 'mobile_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('users', 'encrypted_access_token')
    op.create_table('intraday_ltp',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('instrument', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ltp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('intraday_ltp_pkey'))
    )
    op.create_index(op.f('ix_intraday_ltp_timestamp'), 'intraday_ltp', ['timestamp'], unique=False)
    op.create_table('market_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('instrument', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('short_sma', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('medium_sma', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('long_sma', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('market_data_pkey'))
    )
    op.create_index(op.f('ix_market_data_timestamp'), 'market_data', ['timestamp'], unique=False)
    # ### end Alembic commands ###
