"""Changed access_token to plaintext

Revision ID: 3e62ed4a6329
Revises: 4f6d99a3a359
Create Date: 2025-10-07 18:29:14.755445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e62ed4a6329'
down_revision = '4f6d99a3a359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('access_token',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_column('encrypted_access_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_access_token', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.alter_column('access_token',
               existing_type=sa.String(length=500),
               type_=postgresql.BYTEA(),
               existing_nullable=True)

    # ### end Alembic commands ###
