"""Add is_trial_active to User model

Revision ID: 4eee7b85bc18
Revises: e7fb4f68a1bb
Create Date: 2025-08-20 16:59:18.234075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eee7b85bc18'
down_revision = 'e7fb4f68a1bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trial_active', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_trial_active')

    # ### end Alembic commands ###
