"""Add encrypted client credentials to User model

Revision ID: 5f622ed51115
Revises: f4f642e7b499
Create Date: 2025-08-07 11:29:43.592106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f622ed51115'
down_revision = 'f4f642e7b499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_client_id', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('encrypted_client_secret', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('encrypted_refresh_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_refresh_token', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.drop_column('encrypted_client_secret')
        batch_op.drop_column('encrypted_client_id')

    # ### end Alembic commands ###
