"""empty message

Revision ID: f4f642e7b499
Revises: 99870c5f0c8b
Create Date: 2025-08-06 16:23:43.164672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f642e7b499'
down_revision = '99870c5f0c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_access_token', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('encrypted_refresh_token', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('upstox_access_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upstox_access_token', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
        batch_op.drop_column('encrypted_refresh_token')
        batch_op.drop_column('encrypted_access_token')

    # ### end Alembic commands ###
